import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    menu: {
        flex: 1,
        backgroundColor: 'rgba(36, 36, 36, 0.65)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 999,
        position: 'absolute',
        width: '90%',
        height: 400,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'lightcoral',
    },
    container: {
        width: '95%',
        height: '100%',
        flex: 1,
        alignItems: 'center',
        marginTop: 50,
        marginBottom: 20,
        padding: 30,
    },
    title: {
        color: 'white',
        fontSize: 30,
        position: 'absolute',
        top: 40,
        textShadowColor: 'darkcyan',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 8,
    },
    input: {
        width: '100%',
        height: 40,
        backgroundColor: 'white',
        borderColor: 'white',
        borderWidth: 1,
        borderRadius: 3,
        marginTop: 10,
        marginBottom: 10,
        paddingHorizontal: 8,
        borderWidth: 2,
        borderRadius: 8,
        borderColor: 'darkcyan',

    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        position: 'absolute',
        bottom: 20,
        right: 20,
        marginTop: 0,
    },
    button: {
        backgroundColor: 'white',
        marginTop: 10,
        width: '100%',
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: '#242424',
        borderWidth: 1,
        borderRadius: 5,
    },
    logContainer: {
        width: '95%',
        height: '100%',
        flex: 1,
        alignItems: 'center',
        textAlign: 'center',
        marginTop: 20,
        marginBottom: 20,
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    logText: {
        fontSize: 20,
        marginBottom: 10,
        color: '#242424',
    },
    logTextTitle: {
        fontSize: 24,
        marginBottom: 10,
        color: '#242424',
        fontWeight: 'bold',
    },
    logButton: {
        height: 40,
        backgroundColor: 'lightcoral',
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 15,
        marginHorizontal: 5,
    },
    storeButton: {
        height: 40,
        backgroundColor: 'darkcyan',
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 15,
        marginHorizontal: 5,
    },
});

export default styles;